[platformio]
# Point to your new source folder
src_dir = firmware/src
# It's usually a good idea to move your include folder too
include_dir = firmware/include

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Explicitly tell micro-ROS which transport and distro to use
board_microros_transport = serial
board_microros_distro = humble

lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

# Required for the large micro-ROS binary
board_build.partitions = huge_app.csv

build_flags =
    -DRMW_UXRCE_TRANSPORT=serial